### ISSUE TITLE
restore history

### ISSUE THREAD

**Issue by 1268** [sugawarayuuta/sonnet#10]
currently repo shows 1 commit, please restore the full history

**Comment by sugawarayuuta** [comment]
Thank you for the issue. I was not used to Git. and I completely overwrote the history thinking if was fine to do because It was not working (specifically, it had a linkname mismatch and didn't compile with the latest Go). I'm really sorry I did that. now I understood there was use for it. I'll try to rethink everything before I do things like this to prevent further problems in the future... also, I'll start learning Git from today so that it's easier to collaborate with people in the future. Thanks again.

**Comment by sugawarayuuta** [comment]
Although the entire history itself was small, I was able to recover it. Sorry for inconvenience and Thank you for understanding. Let me know if I can close this issue.

**Comment by 1268** [comment]
cool thank you!
