### ISSUE TITLE
Unmarshalling issue

### ISSUE THREAD

**Issue by hookenz** [sugawarayuuta/sonnet#12]
I wanted to compare this library with Sonic so I downloaded the Sonic benchmarks by cloning the library and adding sonnet into it.

The sonic benchmarks are here.
http://github.com/bytedance/sonic/generic_test

When running the benchmark I get a number of output differences which leads me to think there could be a problem.
It might be worth looking into.

--- FAIL: BenchmarkUnmarshalConcrete/CitmCatalog_Sonnet
    benchmark_test.go:98: Sonnet Unmarshal output mismatch:

--- FAIL: BenchmarkUnmarshalConcrete/TwitterStatus_Sonnet
    benchmark_test.go:98: Sonnet Unmarshal output mismatch:
        got  &{[{{recent ja} Sun Aug 31 00:29:15 +0000 2014 505874924095815700 505874924095815681 @aym0566x

**Comment by sugawarayuuta** [comment]
Thank you for the issue; working on it. My understanding is that there is an issue reusing slice and map elements, when the value is `null`. 
since it doesn't overwrite the memory if it is, It put the decoded value from the previous line. I want to fix it within a day by `SetZero`-ing the elements as needed, but it will come with a performance decrease. I'll try to keep the speed the same if possible.
If you have an idea or other things, feel free to write that down here.

**Comment by sugawarayuuta** [comment]
I believe this was fixed in the latest commit. cloned the repository and the benchmarks ran without mismatches. although this package might not be comparable to Sonic since Sonic uses unsafe and doesn't validate UTF-8, and other things like that.
If you prefer speed over platform compatibility and some minor details I said, then I recommend using that instead.
By the way, Thank you for reporting. Let me know if I can close this issue.

**Comment by hookenz** [comment]
I think you can close it.  Thank you for your awesome work!
